/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coursework1;

import static coursework1.PlayMain.hints;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
import java.util.Random;

/**
 *
 * @author Lakindu
 */
public class PlayMain extends javax.swing.JFrame {

    /**
     * Creates new form PlayMain
     */
   public static String [] stringArr = {"hello", "pillow","button","router", "mobile", "system"};
   public static String [] hints = {"A Greeting","Use when sleepy", "You Click it","Internet conncetion device","Communication Device","Collection of components"};
  
   String comWord =""; //computer guess
   String userWord =""; //user guess
   String fullW=""; //user guess
   char [] charArr = new char [comWord.length()];
   JLabel[] arrayX = new JLabel[10]; //input words to X values
   int tries =0; //counter for tries
    
    public PlayMain() {
        try{
            
        initComponents();
        arrayX [0]=char1;
        arrayX [1]=char2;
        arrayX [2]=char3;
        arrayX [3]=char4;
        arrayX [4]=char5;
        arrayX [5]=char6;
        
        //Create a Random Object
        Random rm = new Random();
        int arrayNo = rm.nextInt(stringArr.length -1)-1;
        
        comWord = stringArr[arrayNo]; //generate a word from the array
        
        String hint = hints[arrayNo];
        jLabel2.setText(hint);
        
        System.out.println("Debug"+comWord);
        
        charArr = comWord.toCharArray(); //convert to character
        System.out.println("Debug "+userWord);
        
        
        //creating for loop to display X's according to word length
       for(int i =0; i<charArr.length;i++){
            arrayX[i].setText("X");
        }
        }
        catch(Exception e){
        }
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblMsg = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        char1 = new javax.swing.JLabel();
        char2 = new javax.swing.JLabel();
        char3 = new javax.swing.JLabel();
        char4 = new javax.swing.JLabel();
        char5 = new javax.swing.JLabel();
        char6 = new javax.swing.JLabel();
        txtfldInput = new javax.swing.JTextField();
        lblTry = new javax.swing.JLabel();
        btnTry = new javax.swing.JButton();
        imgHang = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblMsg.setText("Message");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblMsg)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblMsg)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLayeredPane1.setBackground(new java.awt.Color(204, 255, 255));
        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtfldInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfldInputActionPerformed(evt);
            }
        });
        txtfldInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfldInputKeyPressed(evt);
            }
        });

        lblTry.setText("0");

        btnTry.setText("Try Button");
        btnTry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTry)
                    .addComponent(lblTry)
                    .addComponent(txtfldInput, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(char1)
                        .addGap(18, 18, 18)
                        .addComponent(char2)
                        .addGap(18, 18, 18)
                        .addComponent(char3)
                        .addGap(18, 18, 18)
                        .addComponent(char4, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(char5)
                        .addGap(18, 18, 18)
                        .addComponent(char6)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(char1)
                    .addComponent(char2)
                    .addComponent(char3)
                    .addComponent(char4)
                    .addComponent(char5)
                    .addComponent(char6))
                .addGap(38, 38, 38)
                .addComponent(txtfldInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(lblTry)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(btnTry)
                .addGap(31, 31, 31))
        );
        jLayeredPane1.setLayer(char1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(char2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(char3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(char4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(char5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(char6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtfldInput, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblTry, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnTry, javax.swing.JLayeredPane.DEFAULT_LAYER);

        imgHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coursework1/img/img0.jpg"))); // NOI18N
        imgHang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SimSun-ExtB", 0, 36)); // NOI18N
        jLabel1.setText("Game On!");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Message");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                        .addComponent(imgHang))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addGap(57, 57, 57))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(244, 244, 244))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLayeredPane1)
                    .addComponent(imgHang, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfldInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfldInputKeyPressed
    }//GEN-LAST:event_txtfldInputKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Begin a = new Begin();
        a.setVisible(true); // to open the new jframe
        this.dispose();    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtfldInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfldInputActionPerformed
       
    }//GEN-LAST:event_txtfldInputActionPerformed

    private void btnTryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTryActionPerformed
        int validate=0;
        try{
            //Getting input from the text field and converting it to char
            char input = txtfldInput.getText().charAt(0);
            //Running a for loop to check the input letter matches any of the letters in comWord
            for(int i = 0;i<=charArr.length;i++){
                if(input==charArr[i]){
                    arrayX[i].setText(Character.toString(input));
                    userWord+=Character.toString(input);
                    validate++;
                }

            }
            System.out.println(userWord);

        }
        catch(Exception e){

            System.out.println("c"+fullW);
        }
        //Winning Condition
        triesOutput(validate);
        fullW=(char1.getText()+char2.getText()+char3.getText()+char4.getText()+char5.getText()+char6.getText());
        if(fullW.equals(comWord)){
            JOptionPane.showMessageDialog(null,"Congratulations. You Won!", "Victory",JOptionPane.INFORMATION_MESSAGE, new ImageIcon("/Users/Lakindu/Desktop/Netbeans Designing/CourseWork1/src/coursework1/img/won.png"));
        }
    }//GEN-LAST:event_btnTryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayMain().setVisible(true);
            }
        });
    }
        //Losing Condition
        public void triesOutput(int validate) {
        if(validate ==0){
            tries++;
            lblTry.setText(Integer.toString(tries));
            imageDisplay (tries);
            if(tries==7){
                JOptionPane.showMessageDialog(null, "Game Over", "Lost", JOptionPane.INFORMATION_MESSAGE, new ImageIcon("/Users/Lakindu/Desktop/Netbeans Designing/CourseWork1/src/coursework1/img/lost.png"));
            }
           
        }
               
            
        
    }
     //Image Replacement
    private void imageDisplay(int tries) {
       if (tries == 1){
          imgHang.setIcon (new ImageIcon("/Users/Lakindu/Desktop/Netbeans Designing/CourseWork1/src/coursework1/img/img1.png"));
       }
       else if (tries ==2) {
          imgHang.setIcon (new ImageIcon("/Users/Lakindu/Desktop/Netbeans Designing/CourseWork1/src/coursework1/img/img2.png"));

       }
       else if (tries ==3) {
          imgHang.setIcon (new ImageIcon("/Users/Lakindu/Desktop/Netbeans Designing/CourseWork1/src/coursework1/img/img3.png"));

       }
       else if (tries ==4) {
          imgHang.setIcon (new ImageIcon("/Users/Lakindu/Desktop/Netbeans Designing/CourseWork1/src/coursework1/img/img4.png"));

       }
       else if (tries ==5) {
          imgHang.setIcon (new ImageIcon("/Users/Lakindu/Desktop/Netbeans Designing/CourseWork1/src/coursework1/img/img5.png"));

       }
       else if (tries ==6) {
          imgHang.setIcon (new ImageIcon("/Users/Lakindu/Desktop/Netbeans Designing/CourseWork1/src/coursework1/img/img6.png"));

       }
       else if (tries ==7) {
          imgHang.setIcon (new ImageIcon("/Users/Lakindu/Desktop/Netbeans Designing/CourseWork1/src/coursework1/img/img7.png"));

       }
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTry;
    private javax.swing.JLabel char1;
    private javax.swing.JLabel char2;
    private javax.swing.JLabel char3;
    private javax.swing.JLabel char4;
    private javax.swing.JLabel char5;
    private javax.swing.JLabel char6;
    private javax.swing.JLabel imgHang;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JLabel lblTry;
    private javax.swing.JTextField txtfldInput;
    // End of variables declaration//GEN-END:variables
  
}
